development:
  sessions:
    default:
      database: redstore_dev
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: redstore_dev
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: redstore_test
      hosts:
        - localhost:27017
